#--- Version de L'api Kubernetes (app/v1, v1, ...)
apiVersion: v1
#--- le type d'entité qu'on souhaite créer => des pods
kind: Pod
#--- des informations sur l'objet qu'on crée
metadata:
  name: nginx-redis 
  labels:
    name: nginx-redis
#-- spécifications des conteneurs de notre pod
spec:
  containers:
  - name: c1-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
    ports:
      - containerPort: 80
  - name: c2-redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: mysql
    image: mariadb
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: springboot
    image: arey/springboot-petclinic
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    #----Injecter des variables d'environement à l'interieur du container
    env:
      - name: "SPRING_PROFILES_ACTIVE"
        value: "prod"

      
